apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    project: {{ .Values.projectName }}
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
{{ if eq .Values.appName "frontend" }}
    - port: 9113
      targetPort: 9113
      name: metrics
{{ end }}
